name: Scrape Kings League Website

#on:
#workflow_dispatch:

#repository_dispatch:
#types:
#- webhook

# schedule:
#- cron: '0 */1 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
          run_install: true
      - run: |
          npm run scrape
          git config --global user.email "davidbarcenasmx@gmail.com"
          git config --global user.name "David Barcenas"
          git diff --quiet && git diff --staged --quiet || git commit -am "update leaderboard database"
          git push origin main
